local h = require("keymaps.helpers")

vim.keymap.set("n", "<leader>dd", function()
  h.ensure_dap(); require('dap').continue()
end, { silent = true, desc = "Start/Continue Debug" })
vim.keymap.set("n", "<leader>db", function()
  h.ensure_dap(); require('dap').toggle_breakpoint()
end, { silent = true, desc = "Toggle Breakpoint" })
vim.keymap.set("n", "<leader>do", function()
  h.ensure_dap(); require('dap').step_over()
end, { silent = true, desc = "Step Over" })
vim.keymap.set("n", "<leader>di", function()
  h.ensure_dap(); require('dap').step_into()
end, { silent = true, desc = "Step Into" })
vim.keymap.set("n", "<leader>du", function()
  h.ensure_dap(); require('dapui').toggle()
end, { silent = true, desc = "Toggle DAP UI" })

vim.keymap.set("n", "<leader>dt", function()
  h.ensure_neotest(); require('neotest').run.run()
end, { silent = true, desc = "Run Nearest Test" })
vim.keymap.set("n", "<leader>df", function()
  h.ensure_neotest(); require('neotest').run.run(vim.fn.expand('%'))
end, { silent = true, desc = "Run Test File" })
vim.keymap.set("n", "<leader>do", function()
  h.ensure_neotest(); require('neotest').output.open({ enter = true })
end, { silent = true, desc = "Open Test Output" })
vim.keymap.set("n", "<leader>ds", function()
  h.ensure_neotest(); require('neotest').summary.toggle()
end, { silent = true, desc = "Toggle Test Summary" })
