local h = require("keymaps.helpers")

vim.keymap.set("n", "<leader>ff", function() h.telescope("find_files") end, { desc = "Find files" })
vim.keymap.set("n", "<leader>fr", function() h.telescope("oldfiles") end, { desc = "Recent files" })
vim.keymap.set("n", "<leader>fg", function() h.telescope("live_grep") end, { desc = "Live grep" })
vim.keymap.set("n", "<leader>fb", function() h.telescope("buffers") end, { desc = "Open buffers" })
vim.keymap.set("n", "<leader>fh", function() h.telescope("help_tags") end, { desc = "Help tags" })
vim.keymap.set("n", "<leader>fc", function() h.telescope("current_buffer_fuzzy_find") end, { desc = "Find in current buffer" })
vim.keymap.set("n", "<leader>fd", function() h.telescope("diagnostics") end, { desc = "Diagnostics" })
vim.keymap.set("n", "<leader>fm", function() h.telescope("marks") end, { desc = "Jump to mark" })
vim.keymap.set("n", "<leader>fp", function() h.telescope("project") end, { desc = "Projects" })
vim.keymap.set("n", "<leader>fs", function() h.telescope("grapple tags") end, { desc = "Grapple tags" })
vim.keymap.set("n", "<leader>fz", function() require("plugins.theme.colorscheme").pick() end, { desc = "Themes" })
vim.keymap.set("n", "<leader>ft", function() h.telescope("treesitter") end, { desc = "Symbols (Treesitter)" })
vim.keymap.set("n", "<leader>fT", "<cmd>TodoTelescope<CR>", { desc = "Search TODOs" })
